-- ============================================================================
-- The Tradeyard -- seed real parallel data for base cards
--
-- Populates public.parallels with researched, set-accurate parallel names,
-- print runs, and SKU exclusivity for the 6 base-card sets in card_catalog
-- (2025 Topps Chrome, Cosmic Chrome, Finest, Resurgence, Signature Class,
-- 2026 Topps Flagship). 234 rows total. Run parallels.sql first.
--
-- Insert-set-specific parallel ladders (which can differ from these base-card
-- parallels) are intentionally NOT part of this seed -- a later import.
-- ============================================================================

delete from public.parallels where set_name in (
  '2025 Topps Chrome Football',
  '2025 Topps Cosmic Chrome Football',
  '2025 Topps Finest Football',
  '2025 Topps Resurgence Football',
  '2025 Topps Signature Class Football',
  '2026 Topps Flagship Football'
);

insert into public.parallels
  (set_name, parallel_name, print_run, sku_exclusivity, tier, base_type, sort_order)
values
  ('2025 Topps Chrome Football', 'Refractor', null, null, null, null, 1),
  ('2025 Topps Chrome Football', 'Topps Refractor', null, 'Fanatics Mega exclusive', null, null, 2),
  ('2025 Topps Chrome Football', 'X-Fractor', null, 'Mega exclusive', null, null, 3),
  ('2025 Topps Chrome Football', 'Hot Pink X-Fractor', null, 'Mega exclusive', null, null, 4),
  ('2025 Topps Chrome Football', 'Lime Green X-Fractor', null, 'Mega exclusive', null, null, 5),
  ('2025 Topps Chrome Football', 'Prism Refractor', null, 'Hobby/FDI/Jumbo', null, null, 6),
  ('2025 Topps Chrome Football', 'Neon Pulse Refractor', null, 'Hobby/FDI/Jumbo', null, null, 7),
  ('2025 Topps Chrome Football', 'Pulsar Refractor', null, 'Retail', null, null, 8),
  ('2025 Topps Chrome Football', 'RayWave Refractor', null, 'Value exclusive', null, null, 9),
  ('2025 Topps Chrome Football', 'Red, White, and Blue Refractor', null, 'Value exclusive', null, null, 10),
  ('2025 Topps Chrome Football', 'Football Leather Refractor', null, 'Value exclusive', null, null, 11),
  ('2025 Topps Chrome Football', 'Geometric Refractor', null, 'Delight exclusive', null, null, 12),
  ('2025 Topps Chrome Football', 'Teal Refractor', 299, null, null, null, 13),
  ('2025 Topps Chrome Football', 'Teal Wave Refractor', 299, 'Rookies only', null, null, 14),
  ('2025 Topps Chrome Football', 'Yellow Wave Refractor', 275, null, null, null, 15),
  ('2025 Topps Chrome Football', 'Pink Refractor', 250, null, null, null, 16),
  ('2025 Topps Chrome Football', 'Pink Wave Refractor', 250, null, null, null, 17),
  ('2025 Topps Chrome Football', 'Aqua Refractor', 199, null, null, null, 18),
  ('2025 Topps Chrome Football', 'Aqua Wave Refractor', 199, null, null, null, 19),
  ('2025 Topps Chrome Football', 'Blue Refractor', 150, null, null, null, 20),
  ('2025 Topps Chrome Football', 'Blue Wave Refractor', 150, null, null, null, 21),
  ('2025 Topps Chrome Football', 'Blue Geometric Refractor', 150, 'Delight, Rookies only', null, null, 22),
  ('2025 Topps Chrome Football', 'Blue Football Leather Refractor', 150, 'Value, Rookies only', null, null, 23),
  ('2025 Topps Chrome Football', 'Green Refractor', 99, null, null, null, 24),
  ('2025 Topps Chrome Football', 'Green Lava Refractor', 99, null, null, null, 25),
  ('2025 Topps Chrome Football', 'Green Wave Refractor', 99, null, null, null, 26),
  ('2025 Topps Chrome Football', 'Green Football Leather Refractor', 99, 'Value', null, null, 27),
  ('2025 Topps Chrome Football', 'Green Geometric Refractor', 99, 'Delight, Rookies only', null, null, 28),
  ('2025 Topps Chrome Football', 'Purple Refractor', 75, null, null, null, 29),
  ('2025 Topps Chrome Football', 'Purple Lava Refractor', 75, null, null, null, 30),
  ('2025 Topps Chrome Football', 'Purple Wave Refractor', 75, null, null, null, 31),
  ('2025 Topps Chrome Football', 'Purple Football Leather Refractor', 75, 'Value', null, null, 32),
  ('2025 Topps Chrome Football', 'Purple Geometric Refractor', 75, 'Delight, Rookies only', null, null, 33),
  ('2025 Topps Chrome Football', 'Gold Refractor', 50, null, null, null, 34),
  ('2025 Topps Chrome Football', 'Gold Lava Refractor', 50, null, null, null, 35),
  ('2025 Topps Chrome Football', 'Gold Wave Refractor', 50, null, null, null, 36),
  ('2025 Topps Chrome Football', 'Gold Football Leather Refractor', 50, 'Value', null, null, 37),
  ('2025 Topps Chrome Football', 'Gold Geometric Refractor', 50, 'Delight', null, null, 38),
  ('2025 Topps Chrome Football', 'White Refractor', 30, null, null, null, 39),
  ('2025 Topps Chrome Football', 'Orange Refractor', 25, null, null, null, 40),
  ('2025 Topps Chrome Football', 'Orange Lava Refractor', 25, null, null, null, 41),
  ('2025 Topps Chrome Football', 'Orange Wave Refractor', 25, null, null, null, 42),
  ('2025 Topps Chrome Football', 'Orange Football Leather Refractor', 25, 'Value', null, null, 43),
  ('2025 Topps Chrome Football', 'Orange Geometric Refractor', 25, 'Delight', null, null, 44),
  ('2025 Topps Chrome Football', 'Black Refractor', 10, null, null, null, 45),
  ('2025 Topps Chrome Football', 'Black Lava Refractor', 10, null, null, null, 46),
  ('2025 Topps Chrome Football', 'Black Wave Refractor', 10, null, null, null, 47),
  ('2025 Topps Chrome Football', 'Black Football Leather Refractor', 10, 'Value', null, null, 48),
  ('2025 Topps Chrome Football', 'Black Geometric Refractor', 10, 'Delight', null, null, 49),
  ('2025 Topps Chrome Football', 'Molten Mercury', 6, 'First Day Issue exclusive', null, null, 50),
  ('2025 Topps Chrome Football', 'Frozenfractor', 5, 'Print run unverified - check card in hand', null, null, 51),
  ('2025 Topps Chrome Football', 'Red Refractor', 5, null, null, null, 52),
  ('2025 Topps Chrome Football', 'Red Lava Refractor', 5, null, null, null, 53),
  ('2025 Topps Chrome Football', 'Red Wave Refractor', 5, null, null, null, 54),
  ('2025 Topps Chrome Football', 'Red Football Leather Refractor', 5, 'Value', null, null, 55),
  ('2025 Topps Chrome Football', 'Red Geometric Refractor', 5, 'Delight', null, null, 56),
  ('2025 Topps Chrome Football', 'Tie-Dye Geometric Refractor', 2, 'Delight', null, null, 57),
  ('2025 Topps Chrome Football', 'SuperFractor', 1, null, null, null, 58),
  ('2025 Topps Cosmic Chrome Football', 'Refractor', null, 'Hobby + Lunar', null, null, 1),
  ('2025 Topps Cosmic Chrome Football', 'Nucleus Refractor', null, 'Hobby + Lunar', null, null, 2),
  ('2025 Topps Cosmic Chrome Football', 'White Hole Refractor', null, 'Hobby', null, null, 3),
  ('2025 Topps Cosmic Chrome Football', 'Aqua Equinox Refractor', 199, 'Hobby + Lunar', null, null, 4),
  ('2025 Topps Cosmic Chrome Football', 'Purple Nebula Refractor', 150, 'Hobby + Lunar', null, null, 5),
  ('2025 Topps Cosmic Chrome Football', 'Blue Moon Refractor', 99, 'Hobby + Lunar', null, null, 6),
  ('2025 Topps Cosmic Chrome Football', 'Green Space Dust Refractor', 75, 'Hobby + Lunar', null, null, 7),
  ('2025 Topps Cosmic Chrome Football', 'Gold Interstellar Refractor', 50, 'Hobby + Lunar', null, null, 8),
  ('2025 Topps Cosmic Chrome Football', 'Orange Galactic Refractor', 25, 'Hobby + Lunar', null, null, 9),
  ('2025 Topps Cosmic Chrome Football', 'Black Eclipse Refractor', 10, 'Hobby channel', null, null, 10),
  ('2025 Topps Cosmic Chrome Football', 'Lunar Eclipse Refractor', 10, 'Lunar channel exclusive', null, null, 11),
  ('2025 Topps Cosmic Chrome Football', 'Red Flare Refractor', 5, 'Hobby', null, null, 12),
  ('2025 Topps Cosmic Chrome Football', 'SuperFractor', 1, 'Hobby', null, null, 13),
  ('2025 Topps Finest Football', 'Refractor', null, null, 'Common', null, 1),
  ('2025 Topps Finest Football', 'X-Fractor', null, 'Hobby exclusive, unnumbered', 'Common', null, 2),
  ('2025 Topps Finest Football', 'Oil Spill Refractor', null, 'Hobby exclusive, unnumbered', 'Common', null, 3),
  ('2025 Topps Finest Football', 'Sky Blue Refractor', 325, null, 'Common', null, 4),
  ('2025 Topps Finest Football', 'Purple Refractor', 250, null, 'Common', null, 5),
  ('2025 Topps Finest Football', 'Blue Refractor', 200, null, 'Common', null, 6),
  ('2025 Topps Finest Football', 'Purple X-Fractor', 150, null, 'Common', null, 7),
  ('2025 Topps Finest Football', 'Blue X-Fractor', 99, null, 'Common', null, 8),
  ('2025 Topps Finest Football', 'Green Refractor', 75, null, 'Common', null, 9),
  ('2025 Topps Finest Football', 'Gold Refractor', 50, null, 'Common', null, 10),
  ('2025 Topps Finest Football', 'Orange Refractor', 25, null, 'Common', null, 11),
  ('2025 Topps Finest Football', 'Black Refractor', 20, null, 'Common', null, 12),
  ('2025 Topps Finest Football', 'Red Refractor', 10, null, 'Common', null, 13),
  ('2025 Topps Finest Football', 'SuperFractor', 1, null, 'Common', null, 14),
  ('2025 Topps Finest Football', 'Sky Blue Geometric', 325, 'Breaker/Delight exclusive', 'Common', null, 15),
  ('2025 Topps Finest Football', 'Purple Geometric', 250, 'Breaker/Delight exclusive', 'Common', null, 16),
  ('2025 Topps Finest Football', 'Blue Geometric', 200, 'Breaker/Delight exclusive', 'Common', null, 17),
  ('2025 Topps Finest Football', 'Green Geometric', 75, 'Breaker/Delight exclusive', 'Common', null, 18),
  ('2025 Topps Finest Football', 'Gold Geometric', 50, 'Breaker/Delight exclusive', 'Common', null, 19),
  ('2025 Topps Finest Football', 'Orange Geometric', 25, 'Breaker/Delight exclusive', 'Common', null, 20),
  ('2025 Topps Finest Football', 'Black Geometric', 20, 'Breaker/Delight exclusive', 'Common', null, 21),
  ('2025 Topps Finest Football', 'Red Geometric', 10, 'Breaker/Delight exclusive', 'Common', null, 22),
  ('2025 Topps Finest Football', 'Refractor', null, null, 'Uncommon', null, 1),
  ('2025 Topps Finest Football', 'X-Fractor', null, 'Hobby exclusive, unnumbered', 'Uncommon', null, 2),
  ('2025 Topps Finest Football', 'Oil Spill Refractor', null, 'Hobby exclusive, unnumbered', 'Uncommon', null, 3),
  ('2025 Topps Finest Football', 'Sky Blue Refractor', 250, null, 'Uncommon', null, 4),
  ('2025 Topps Finest Football', 'Purple Refractor', 200, null, 'Uncommon', null, 5),
  ('2025 Topps Finest Football', 'Blue Refractor', 150, null, 'Uncommon', null, 6),
  ('2025 Topps Finest Football', 'Purple X-Fractor', 99, null, 'Uncommon', null, 7),
  ('2025 Topps Finest Football', 'Blue X-Fractor', 75, null, 'Uncommon', null, 8),
  ('2025 Topps Finest Football', 'Green Refractor', 35, null, 'Uncommon', null, 9),
  ('2025 Topps Finest Football', 'Gold Refractor', 25, null, 'Uncommon', null, 10),
  ('2025 Topps Finest Football', 'Orange Refractor', 20, null, 'Uncommon', null, 11),
  ('2025 Topps Finest Football', 'Black Refractor', 15, null, 'Uncommon', null, 12),
  ('2025 Topps Finest Football', 'Red Refractor', 5, null, 'Uncommon', null, 13),
  ('2025 Topps Finest Football', 'SuperFractor', 1, null, 'Uncommon', null, 14),
  ('2025 Topps Finest Football', 'Sky Blue Geometric', 250, 'Breaker/Delight exclusive', 'Uncommon', null, 15),
  ('2025 Topps Finest Football', 'Purple Geometric', 200, 'Breaker/Delight exclusive', 'Uncommon', null, 16),
  ('2025 Topps Finest Football', 'Blue Geometric', 150, 'Breaker/Delight exclusive', 'Uncommon', null, 17),
  ('2025 Topps Finest Football', 'Green Geometric', 35, 'Breaker/Delight exclusive', 'Uncommon', null, 18),
  ('2025 Topps Finest Football', 'Gold Geometric', 25, 'Breaker/Delight exclusive', 'Uncommon', null, 19),
  ('2025 Topps Finest Football', 'Orange Geometric', 20, 'Breaker/Delight exclusive', 'Uncommon', null, 20),
  ('2025 Topps Finest Football', 'Black Geometric', 15, 'Breaker/Delight exclusive', 'Uncommon', null, 21),
  ('2025 Topps Finest Football', 'Red Geometric', 5, 'Breaker/Delight exclusive', 'Uncommon', null, 22),
  ('2025 Topps Finest Football', 'Refractor', null, null, 'Rare', null, 1),
  ('2025 Topps Finest Football', 'X-Fractor', null, 'Hobby exclusive, unnumbered', 'Rare', null, 2),
  ('2025 Topps Finest Football', 'Oil Spill Refractor', null, 'Hobby exclusive, unnumbered', 'Rare', null, 3),
  ('2025 Topps Finest Football', 'Sky Blue Refractor', 150, null, 'Rare', null, 4),
  ('2025 Topps Finest Football', 'Purple Refractor', 125, null, 'Rare', null, 5),
  ('2025 Topps Finest Football', 'Blue Refractor', 99, null, 'Rare', null, 6),
  ('2025 Topps Finest Football', 'Purple X-Fractor', 75, null, 'Rare', null, 7),
  ('2025 Topps Finest Football', 'Blue X-Fractor', 49, null, 'Rare', null, 8),
  ('2025 Topps Finest Football', 'Green Refractor', 25, null, 'Rare', null, 9),
  ('2025 Topps Finest Football', 'Gold Refractor', 20, null, 'Rare', null, 10),
  ('2025 Topps Finest Football', 'Orange Refractor', 15, null, 'Rare', null, 11),
  ('2025 Topps Finest Football', 'Black Refractor', 10, null, 'Rare', null, 12),
  ('2025 Topps Finest Football', 'Red Refractor', 3, null, 'Rare', null, 13),
  ('2025 Topps Finest Football', 'SuperFractor', 1, null, 'Rare', null, 14),
  ('2025 Topps Finest Football', 'Sky Blue Geometric', 150, 'Breaker/Delight exclusive', 'Rare', null, 15),
  ('2025 Topps Finest Football', 'Purple Geometric', 125, 'Breaker/Delight exclusive', 'Rare', null, 16),
  ('2025 Topps Finest Football', 'Blue Geometric', 99, 'Breaker/Delight exclusive', 'Rare', null, 17),
  ('2025 Topps Finest Football', 'Green Geometric', 25, 'Breaker/Delight exclusive', 'Rare', null, 18),
  ('2025 Topps Finest Football', 'Gold Geometric', 20, 'Breaker/Delight exclusive', 'Rare', null, 19),
  ('2025 Topps Finest Football', 'Orange Geometric', 15, 'Breaker/Delight exclusive', 'Rare', null, 20),
  ('2025 Topps Finest Football', 'Black Geometric', 10, 'Breaker/Delight exclusive', 'Rare', null, 21),
  ('2025 Topps Finest Football', 'Red Geometric', 3, 'Breaker/Delight exclusive', 'Rare', null, 22),
  ('2025 Topps Resurgence Football', 'Refractor', null, null, null, null, 1),
  ('2025 Topps Resurgence Football', 'High Voltage', null, 'Hobby, unnumbered', null, null, 2),
  ('2025 Topps Resurgence Football', 'Prism', null, 'Mega + Value Blaster, unnumbered', null, null, 3),
  ('2025 Topps Resurgence Football', 'Blue & Orange Spark', null, 'Mega Box exclusive (1:3 packs)', null, null, 4),
  ('2025 Topps Resurgence Football', 'Sky Blue & Pink Shock', null, 'Value Blaster exclusive (1:8 packs)', null, null, 5),
  ('2025 Topps Resurgence Football', 'Silver Static', null, 'Delight exclusive (1:4 packs)', null, null, 6),
  ('2025 Topps Resurgence Football', 'Surge', 425, null, null, null, 7),
  ('2025 Topps Resurgence Football', 'Black & White Surge', 399, null, null, null, 8),
  ('2025 Topps Resurgence Football', 'Bronze Surge', 375, null, null, null, 9),
  ('2025 Topps Resurgence Football', 'Magenta Surge', 299, null, null, null, 10),
  ('2025 Topps Resurgence Football', 'Navy Surge', 275, null, null, null, 11),
  ('2025 Topps Resurgence Football', 'Aqua Surge', 250, null, null, null, 12),
  ('2025 Topps Resurgence Football', 'Yellow Surge', 225, null, null, null, 13),
  ('2025 Topps Resurgence Football', 'Crimson Surge', 199, null, null, null, 14),
  ('2025 Topps Resurgence Football', 'Green Surge', 175, null, null, null, 15),
  ('2025 Topps Resurgence Football', 'Blue Surge', 99, null, null, null, 16),
  ('2025 Topps Resurgence Football', 'Gold Power Surge', 50, null, null, null, 17),
  ('2025 Topps Resurgence Football', 'Orange Power Surge', 25, null, null, null, 18),
  ('2025 Topps Resurgence Football', 'Lime Green Power Surge', 15, null, null, null, 19),
  ('2025 Topps Resurgence Football', 'Pink Power Surge', 10, null, null, null, 20),
  ('2025 Topps Resurgence Football', 'Red Power Surge', 5, null, null, null, 21),
  ('2025 Topps Resurgence Football', 'SuperFractor', 1, null, null, null, 22),
  ('2025 Topps Resurgence Football', 'Gold Static', 50, 'Delight exclusive', null, null, 23),
  ('2025 Topps Resurgence Football', 'Orange Static', 25, 'Delight exclusive', null, null, 24),
  ('2025 Topps Resurgence Football', 'Lime Green Static', 15, 'Delight exclusive', null, null, 25),
  ('2025 Topps Resurgence Football', 'Pink Static', 10, 'Delight exclusive', null, null, 26),
  ('2025 Topps Resurgence Football', 'Red Static', 5, 'Delight exclusive', null, null, 27),
  ('2025 Topps Resurgence Football', 'Black Static', 2, 'Delight exclusive', null, null, 28),
  ('2025 Topps Signature Class Football', 'Base Refractor', null, null, null, 'Chrome', 1),
  ('2025 Topps Signature Class Football', 'Silver', 275, null, null, 'Chrome', 2),
  ('2025 Topps Signature Class Football', 'Magenta', 250, null, null, 'Chrome', 3),
  ('2025 Topps Signature Class Football', 'Teal', 225, null, null, 'Chrome', 4),
  ('2025 Topps Signature Class Football', 'Lime Green', 175, null, null, 'Chrome', 5),
  ('2025 Topps Signature Class Football', 'Green', 150, null, null, 'Chrome', 6),
  ('2025 Topps Signature Class Football', 'Purple', 100, null, null, 'Chrome', 7),
  ('2025 Topps Signature Class Football', 'Orange', 50, null, null, 'Chrome', 8),
  ('2025 Topps Signature Class Football', 'Orange Lava', 50, null, null, 'Chrome', 9),
  ('2025 Topps Signature Class Football', 'Gold', 35, null, null, 'Chrome', 10),
  ('2025 Topps Signature Class Football', 'Red', 25, null, null, 'Chrome', 11),
  ('2025 Topps Signature Class Football', 'Red Lava', 25, null, null, 'Chrome', 12),
  ('2025 Topps Signature Class Football', 'Black', 10, null, null, 'Chrome', 13),
  ('2025 Topps Signature Class Football', 'Black Gold', 10, null, null, 'Chrome', 14),
  ('2025 Topps Signature Class Football', 'Blue', 5, null, null, 'Chrome', 15),
  ('2025 Topps Signature Class Football', 'Superfractor', 1, null, null, 'Chrome', 16),
  ('2025 Topps Signature Class Football', 'Blue & Yellow', null, 'Retail exclusive (1:5 Value Blaster; 1:5 Mega)', null, 'Paper', 17),
  ('2025 Topps Signature Class Football', 'Green & Purple', null, 'Value Blaster exclusive (1:7)', null, 'Paper', 18),
  ('2025 Topps Signature Class Football', 'Red & Black', null, 'Mega exclusive (1:7)', null, 'Paper', 19),
  ('2025 Topps Signature Class Football', 'Kaleidoscope', null, 'Value Box exclusive', null, 'Chrome', 20),
  ('2025 Topps Signature Class Football', 'Pandora', null, 'Mega Box exclusive', null, 'Chrome', 21),
  ('2026 Topps Flagship Football', 'Rainbow Foil', null, 'Hobby/Jumbo + wide distribution, unnumbered', null, null, 1),
  ('2026 Topps Flagship Football', 'Holo Foil', null, 'Retail (Blaster/Mega/Fanatics/Hanger/Fat Pack), unnumbered', null, null, 2),
  ('2026 Topps Flagship Football', 'Topps Foilboard', null, 'Fanatics Value exclusive, unnumbered', null, null, 3),
  ('2026 Topps Flagship Football', 'Aqua Holo Foil', null, 'Retail, unnumbered', null, null, 4),
  ('2026 Topps Flagship Football', 'Diamante Foil', null, 'Hanger exclusive, unnumbered', null, null, 5),
  ('2026 Topps Flagship Football', 'Pink Diamante', null, 'Hanger exclusive, unnumbered', null, null, 6),
  ('2026 Topps Flagship Football', 'Sandglitter', null, 'Jumbo exclusive, unnumbered', null, null, 7),
  ('2026 Topps Flagship Football', 'Football Parallel (Football Leather)', null, 'Value exclusive, unnumbered', null, null, 8),
  ('2026 Topps Flagship Football', 'Silver Crackle', null, 'Mega exclusive, unnumbered', null, null, 9),
  ('2026 Topps Flagship Football', 'White & Blue', null, 'Walmart Mega exclusive, unnumbered', null, null, 10),
  ('2026 Topps Flagship Football', 'Purple & Blue', null, 'Walmart Mega exclusive, unnumbered', null, null, 11),
  ('2026 Topps Flagship Football', 'Blue & Yellow (Flagship)', null, 'Walmart Mega exclusive, unnumbered', null, null, 12),
  ('2026 Topps Flagship Football', 'Green & Blue', null, 'Walmart Mega exclusive, unnumbered', null, null, 13),
  ('2026 Topps Flagship Football', 'Gold & Blue', null, 'Walmart Mega exclusive, unnumbered', null, null, 14),
  ('2026 Topps Flagship Football', 'Orange & Blue', null, 'Walmart Mega exclusive, unnumbered', null, null, 15),
  ('2026 Topps Flagship Football', 'Black & Blue', null, 'Walmart Mega exclusive, unnumbered', null, null, 16),
  ('2026 Topps Flagship Football', 'Union Jack Rainbow Foil', null, 'London Mega exclusive, unnumbered', null, null, 17),
  ('2026 Topps Flagship Football', 'Union Jack Blue Rainbow Foil', null, 'London Mega exclusive, unnumbered', null, null, 18),
  ('2026 Topps Flagship Football', 'Big Ben', null, 'London Mega exclusive, unnumbered', null, null, 19),
  ('2026 Topps Flagship Football', 'Tudor Rose', null, 'London Mega exclusive, unnumbered', null, null, 20),
  ('2026 Topps Flagship Football', 'Crown Jewels', null, 'London Mega exclusive, unnumbered', null, null, 21),
  ('2026 Topps Flagship Football', 'Gold', 2026, null, null, null, 22),
  ('2026 Topps Flagship Football', 'Pink Holo Foil', 1200, 'Retail', null, null, 23),
  ('2026 Topps Flagship Football', 'Green Rainbow Foil', 99, null, null, null, 24),
  ('2026 Topps Flagship Football', 'Football Green', 99, 'Value', null, null, 25),
  ('2026 Topps Flagship Football', 'Green Holo Foil', 99, 'Retail', null, null, 26),
  ('2026 Topps Flagship Football', 'Independence Day', 76, null, null, null, 27),
  ('2026 Topps Flagship Football', 'Black', 70, null, null, null, 28),
  ('2026 Topps Flagship Football', 'Sandglitter Gold', 50, 'Jumbo', null, null, 29),
  ('2026 Topps Flagship Football', 'Gold Diamante', 50, 'Hanger', null, null, 30),
  ('2026 Topps Flagship Football', 'Gold Rainbow Foil', 50, null, null, null, 31),
  ('2026 Topps Flagship Football', 'Football Gold', 50, 'Value', null, null, 32),
  ('2026 Topps Flagship Football', 'Gold Holo Foil', 50, 'Retail', null, null, 33),
  ('2026 Topps Flagship Football', 'Canvas', 50, null, null, null, 34),
  ('2026 Topps Flagship Football', 'Sandglitter Orange', 25, 'Jumbo', null, null, 35),
  ('2026 Topps Flagship Football', 'Orange Diamante Foil', 25, 'Hanger', null, null, 36),
  ('2026 Topps Flagship Football', 'Orange Rainbow Foil', 25, null, null, null, 37),
  ('2026 Topps Flagship Football', 'Football Orange', 25, 'Value', null, null, 38),
  ('2026 Topps Flagship Football', 'Orange Holo Foil', 25, 'Retail', null, null, 39),
  ('2026 Topps Flagship Football', 'Camo', 25, null, null, null, 40),
  ('2026 Topps Flagship Football', 'Sandglitter Black', 10, 'Jumbo', null, null, 41),
  ('2026 Topps Flagship Football', 'Black Diamante', 10, 'Hanger', null, null, 42),
  ('2026 Topps Flagship Football', 'Black Rainbow Foil', 10, null, null, null, 43),
  ('2026 Topps Flagship Football', 'Red Diamante', 5, 'Hanger', null, null, 44),
  ('2026 Topps Flagship Football', 'Red Rainbow Foil', 5, null, null, null, 45),
  ('2026 Topps Flagship Football', 'Rose Gold Holo Foil', 1, null, null, null, 46),
  ('2026 Topps Flagship Football', 'Foilfractor', 1, null, null, null, 47),
  ('2026 Topps Flagship Football', 'SuperFractor', 1, null, null, null, 48);
